version: '2'
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - cyclop
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wrapcheck
    - funcorder
    - iotamixing
    - modernize
    - unqueryvet
  settings:
    revive:
      rules:
        - name: exported
          severity: warning
          arguments:
            - 'disable-checks-on-functions'
            - 'disable-checks-on-methods'
            - 'disable-checks-on-types'
            - 'disable-checks-on-constants'
    cyclop:
      max-complexity: 25
    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - cloud.google.com/go/civil
            - cloud.google.com/go/spanner
            - cloud.google.com/go/logging
            - github.com/cccteam
            - github.com/cenkalti
            - github.com/docker
            - github.com/dslipak
            - github.com/exaring/otelpgx
            - github.com/georgysavva
            - github.com/go-playground
            - github.com/go-test
            - github.com/gofrs/uuid
            - github.com/golang
            - github.com/google
            - github.com/gorilla/securecookie
            - github.com/goware/emailx
            - github.com/jtwatson
            - github.com/korylprince
            - github.com/spf13/cobra
            - github.com/testcontainers
            - go.opentelemetry.io/otel
            - github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace
            - go.opentelemetry.io/contrib/detectors/gcp
            - go.uber.org/mock
            - golang.org/x/crypto/pbkdf2
            - google.golang.org/api/iterator
            - google.golang.org/api/option
            - github.com/zredinger-ccc/migrate
            - github.com/sethvargo/go-envconfig
            - cloud.google.com/go/cloudbuild/apiv2
            - $gostd
    dupl:
      threshold: 100
    exhaustive:
      default-signifies-exhaustive: true
    exhaustruct:
      exclude:
        - 'github.com/spf13/cobra.Command'
        - 'github.com/sethvargo/go-envconfig.Config'
    funlen:
      lines: 100
      statements: 50
    gocognit:
      min-complexity: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 25
    godox:
      keywords:
        - TODO
        - BUG
    misspell:
      locale: US
    nestif:
      min-complexity: 10
    tagalign:
      order:
        - json
        - spanner
    tagliatelle:
      case:
        rules:
          json: camel
        use-field-name: true
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .Cause(
        - .RetryableError(
      ignore-package-globs:
        - github.com/cccteam/httpio*
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - exhaustruct
          - funlen
          - gochecknoglobals
          - gochecknoinits
          - gocognit
          - goconst
          - gocyclo
          - lll
          - mnd
          - nlreturn
          - scopelint
        path: _test\.go
      - linters:
          - errcheck
        text: Rollback
      - linters:
          - gomoddirectives
        path: go\.mod
        text: replacement are not allowed
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    generated: lax
    paths:
      - gui/node_modules
      - third_party$
      - builtin$
      - examples$
  settings:
    golines:
      # Target maximum line length.
      # Default: 100
      max-len: 200